os: linux
jobs:
  include:
  - language: node_js
    node_js: 12
    cache: yarn
    stage: test
    before_install: cd frontend
    install: yarn install
    script: yarn test
    after_script:
    - curl -Ls -o codacy-coverage-reporter "$(curl -Ls https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest
      | jq -r '.assets | map({name, browser_download_url} | select(.name | contains("codacy-coverage-reporter-linux")))
      | .[0].browser_download_url')"
    - chmod +x codacy-coverage-reporter
    - "./codacy-coverage-reporter report -r frontend/coverage/clover.xml"
  - language: python
    python: 3.7.6
    cache: pip
    stage: test
    before_install:
    - openssl aes-256-cbc -K $encrypted_bf57d00e42e8_key -iv $encrypted_bf57d00e42e8_iv
      -in firebase.json.enc -out backend/firebase.json -d
    - cd backend
    install: pip install -r requirements.txt
    script: coverage run --omit "*/venv/*,manage.py"  manage.py test && coverage xml
    after_script:
    - curl -Ls -o codacy-coverage-reporter "$(curl -Ls https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest
      | jq -r '.assets | map({name, browser_download_url} | select(.name | contains("codacy-coverage-reporter-linux")))
      | .[0].browser_download_url')"
    - chmod +x codacy-coverage-reporter
    - "./codacy-coverage-reporter report -r backend/coverage.xml"
  - stage: deploy
    if: branch = dev and type = push
    language: node_js
    node_js: 12
    cache: yarn
    services:
    - docker
    before_install:
    - openssl aes-256-cbc -K $encrypted_bf57d00e42e8_key -iv $encrypted_bf57d00e42e8_iv
      -in firebase.json.enc -out backend/firebase.json -d
    - cd frontend
    install:
    - yarn install
    before_script:
    - yarn build
    script:
    - docker build -t registry.heroku.com/jelszo-novel-dev/web .
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker push registry.heroku.com/jelszo-novel-dev/web

