# Generated by Django 3.0.4 on 2020-03-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=32, unique=True)),
                ('isAdmin', models.BooleanField(default=False)),
                ('isAnonymous', models.BooleanField(default=True)),
                ('isAuthenticated', models.BooleanField(default=True)),
                ('favorites', models.ManyToManyField(to='novel.Novel')),
            ],
        ),
    ]
