# Generated by Django 3.0.4 on 2020-04-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authorization', '0002_auto_20200326_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Unknown', max_length=32),
        ),
    ]
