# Generated by Django 3.0.5 on 2020-05-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authorization', '0004_auto_20200529_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banned',
            field=models.BooleanField(default=False),
        ),
    ]
