# Generated by Django 3.0.7 on 2020-06-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authorization', '0005_user_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Anonymous', max_length=32),
        ),
    ]
