# Generated by Django 3.0.5 on 2020-05-29 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('novel', '0001_initial'),
        ('authorization', '0004_auto_20200529_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('writtenAt', models.DateTimeField(auto_now_add=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Novel')),
                ('parentComment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comment.Comment')),
                ('sender', models.ForeignKey(on_delete=models.SET('[törölt]'), to='authorization.User')),
            ],
        ),
    ]
