# Generated by Django 3.0.5 on 2020-05-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authorization', '0004_auto_20200529_1825'),
        ('comment', '0002_auto_20200529_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=models.SET('[törölt]'), related_name='recipient',
                                    to='authorization.User'),
        ),
    ]
