# Generated by Django 3.0.5 on 2020-05-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authorization', '0004_auto_20200529_1825'),
        ('comment', '0003_comment_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='liked',
            field=models.ManyToManyField(related_name='liked', to='authorization.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sender',
            field=models.ForeignKey(on_delete=models.SET('[törölt]'), related_name='sender', to='authorization.User'),
        ),
    ]
