# Generated by Django 3.0.7 on 2020-06-12 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authorization', '0005_user_banned'),
        ('comment', '0004_auto_20200529_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='liked',
            field=models.ManyToManyField(blank=True, related_name='liked', to='authorization.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parentComment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='comment.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('[törölt]'), related_name='recipient',
                                    to='authorization.User'),
        ),
    ]
