# Generated by Django 3.0.7 on 2020-06-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authorization', '0006_auto_20200616_2151'),
        ('comment', '0005_auto_20200612_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(5), related_name='recipient',
                                    to='authorization.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sender',
            field=models.ForeignKey(on_delete=models.SET(5), related_name='sender', to='authorization.User'),
        ),
    ]
