# Generated by Django 3.0.7 on 2020-06-18 12:23

import comment.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0006_auto_20200616_2151'),
        ('comment', '0006_auto_20200617_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(comment.models.get_deleted_user), related_name='recipient', to='authorization.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sender',
            field=models.ForeignKey(on_delete=models.SET(comment.models.get_deleted_user), related_name='sender', to='authorization.User'),
        ),
    ]
