# Generated by Django 3.0.4 on 2020-03-25 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('path', models.CharField(max_length=150, unique=True)),
                ('lore', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('uploadedAt', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField()),
                ('lang', models.CharField(choices=[('HU', 'Hungarian'), ('EN', 'English')], default='HU', max_length=2)),
            ],
        ),
    ]
