# Generated by Django 3.0.7 on 2020-06-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('value', models.TextField()),
            ],
        ),
    ]
