name: Commit action

on: 
  push:
    branches:    
      - dev

jobs:

  frontend_test:

    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: yarn ci
      run: yarn install --frozen-lockfile
      working-directory: ${{ env.working-directory }}
        
    - name: yarn test
      run: yarn test 
      working-directory: ${{ env.working-directory }}
      env:
        CI: true
        
    - name: yarn install
      run: yarn install --frozen-lockfile
      working-directory: ${{ env.working-directory }}
    
    - name: yarn lint
      run: yarn lint
      working-directory: ${{ env.working-directory }}

    - uses: actions/setup-ruby@v1
    - name: Send Webhook Notification
      if: always()
      env:
        JOB_STATUS: ${{ job.status }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        WORKFLOW_NAME: ${{ github.workflow }}
      run: |
        git clone https://github.com/DiscordHooks/github-actions-discord-webhook.git webhook
        bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
      shell: bash
