name: NPM test

on: 
  push:
    branches:    
      - dev
  pull_request:
    branches: 
      - master
  

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: yarn ci
      run: |
        yarn install --frozen-lockfile
      working-directory: ${{ env.working-directory }}
        
    - name: yarn test
      run: |
        yarn test 
      working-directory: ${{ env.working-directory }}
      env:
        CI: true
