name: Yarn check & Deploy to Heroku

on: 
  push:
    branches:    
      - dev

  pull_request:
    branches:
      - master

jobs:

  test:

    runs-on: ubuntu-latest
    env:
      frontend-directory: ./frontend
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: yarn install
      run: yarn install --frozen-lockfile
      working-directory: ${{ env.frontend-directory }}
        
    - name: yarn test
      run: yarn test 
      working-directory: ${{ env.frontend-directory }}
      env:
        CI: true

    - name: send discord success message
      if: success()
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID_SUCCESS }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN_SUCCESS }}
        avatar_url: "https://i.imgur.com/YBD6GVz.png"
        color: "#2ECC71"
        username: "Novel Check Bot"
        message: "`Test` has passed."


    - name: send discord failure message
      if: failure()
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID_FAIL }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN_FAIL }}
        avatar_url: "https://i.imgur.com/66VzOSm.png"
        color: "#E74C3C"
        username: "Novel Check Bot"
        message: "`Test` has failed."

  lint:
        
    runs-on: ubuntu-latest
    env:
      frontend-directory: ./frontend
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: yarn install
      run: yarn install --frozen-lockfile
      working-directory: ${{ env.frontend-directory }}
    
    - name: yarn lint
      run: yarn lint
      working-directory: ${{ env.frontend-directory }}

    - name: send discord success message
      if: success()
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID_SUCCESS }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN_SUCCESS }}
        avatar_url: "https://i.imgur.com/YBD6GVz.png"
        color: "#2ECC71"
        username: "Novel Check Bot"
        message: "`Lint` has passed."


    - name: send discord failure message
      if: failure()
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID_FAIL }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN_FAIL }}
        avatar_url: "https://i.imgur.com/66VzOSm.png"
        color: "#E74C3C"
        username: "Novel Check Bot"
        message: "`Lint` has failed."

  deploy:

    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    env:
      frontend-directory: ./frontend
      backend-directory: ./backend
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: yarn install
      run: yarn install --frozen-lockfile
      working-directory: ${{ env.frontend-directory }}
      
    - name: yarn build
      run: yarn run build --if-present
      working-directory: ${{ env.frontend-directory }}

    - name: install libpq-dev
      run: sudo apt update && sudo apt install libpq-dev

    - name: copy build files
      run: mkdir backend/frontend && cp frontend/build/* backend/frontend/ -r

    - name: add firebase secrets
      run: gpg --quiet --batch --yes --decrypt --passphrase=${{secrets.FIREBASE_DECRYPT_KEY}} --output backend/firebase.json firebase.json

    - name: setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: pip install
      run: pip3 install -r backend/requirements.txt

    - name: python test
      run: python3 manage.py test
      working-directory: ${{ env.backend-directory }}

    - name: git init
      run: git init
      working-directory: ${{ env.backend-directory }}

    - name: git config
      run: git config --global user.name jelszo &&  git config --global user.email support@jelszo.co

    
    - name: Add remote origin
      run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      working-directory: ${{ env.backend-directory }}
    
    - name: git pull just because why not
      run: git pull heroku master
      
    - name: git add
      run: git add .
      working-directory: ${{ env.backend-directory }}

    - name: git commit
      run: git commit -m "deploy"
      working-directory: ${{ env.backend-directory }}

    - name: Deploy to Heroku
      run: git push --set-upstream heroku master
      working-directory: ${{ env.backend-directory }}

    - name: send discord success message
      if: success()
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID_SUCCESS }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN_SUCCESS }}
        avatar_url: "https://i.imgur.com/YBD6GVz.png"
        color: "#2ECC71"
        username: "Novel Check Bot"
        message: "`Deploy` has done."


    - name: send discord failure message
      if: failure()
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID_FAIL }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN_FAIL }}
        avatar_url: "https://i.imgur.com/66VzOSm.png"
        color: "#E74C3C"
        username: "Novel Check Bot"
        message: "`Deploy` has failed."