name: Yarn check

on: 
  push:
    branches:    
      - dev

  pull_request:
    branches:
      - master

jobs:

  test:

    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: yarn ci
      run: yarn install --frozen-lockfile
      working-directory: ${{ env.working-directory }}
        
    - name: yarn test
      run: yarn test 
      working-directory: ${{ env.working-directory }}
      env:
        CI: true

    - uses: actions/checkout@master
    - name: send discord failure message
      if: failure()
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        avatar_url: "./actions/github-marks/red.png"
        color: "#E74C3C"
        message: "Yarn `test` check didn't pass."

  discord-test:

    needs: test
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend

    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - uses: actions/setup-ruby@v1
    - name: send discord success message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        avatar_url: "./actions/github-marks/green.png"
        color: "#2ECC71"
        message: "Yarn `test` check has passed."

  lint:
        
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: yarn install
      run: yarn install --frozen-lockfile
      working-directory: ${{ env.working-directory }}
    
    - name: yarn lint
      run: yarn lint
      working-directory: ${{ env.working-directory }}

    - uses: actions/setup-ruby@v1
    - name: send discord success message
      if: success()
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        avatar_url: "./actions/github-marks/green.png"
        color: "#2ECC71"
        message: "Yarn `linter` check has passed."

    - uses: actions/checkout@master
    - name: send discord failure message
      if: failure()
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        avatar_url: "https://mediaklikk.hu/wp-content/uploads/sites/4/2016/04/KissBenedekMtnegyzet-400x400.png"
        color: "#E74C3C"
        message: "Yarn `linter` check didn't pass."

  discord-linter:

    needs: lint
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend

    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - uses: actions/setup-ruby@v1
    - name: send discord success message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
        avatar_url: "./actions/github-marks/green.png"
        color: "#2ECC71"
        message: "Yarn `linter` check has passed."