name: NPM test

on: 
  push:
    branches:    
      - dev 

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    
    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: npm ci
      run: |
        npm ci
      working-directory: ${{ env.working-directory }}
        
    - name: npm test
      run: |
        npm test
      working-directory: ${{ env.working-directory }}
