name: Yarn check

on: 
  push:
    branches:    
      - dev

  pull_request:
    branches:
      - master

jobs:

  test:

    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: yarn ci
      run: yarn install --frozen-lockfile
      working-directory: ${{ env.working-directory }}
        
    - name: yarn test
      run: yarn test 
      working-directory: ${{ env.working-directory }}
      env:
        CI: true

    - name: set success variable
      if: success()
      run: |
      env:
        status: passed.
        color-code: "#2ECC71"

    - name: set failure variable
      if: failure()
      run: |
      env:
        status: failed.
        color_code: "#2ECC71"

    - name: send discord message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID_SUCCESS }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN_SUCCESS }}
        avatar_url: "https://i.imgur.com/YBD6GVz.png"
        color: $color_code
        username: "Novel Check Bot"
        message: "`Test` has " 
        args: $status

  lint:
        
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: yarn install
      run: yarn install --frozen-lockfile
      working-directory: ${{ env.working-directory }}
    
    - name: yarn lint
      run: yarn lint
      working-directory: ${{ env.working-directory }}

    - name: set success variable
      if: success()
      run: |
      env:
        status: passed.
        color-code: "#2ECC71"

    - name: set failure variable
      if: failure()
      run: |
      env:
        status: failed.
        color_code: "#2ECC71"

    - name: send discord message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID_SUCCESS }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN_SUCCESS }}
        avatar_url: "https://i.imgur.com/YBD6GVz.png"
        color: $color_code
        username: "Novel Check Bot"
        message: "`Lint` has " 
        args: $status