name: Yarn check

on: 
  push:
    branches:    
      - dev

  pull_request:
    branches:
      - master

jobs:

  test:

    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: yarn ci
      run: yarn install --frozen-lockfile
      working-directory: ${{ env.working-directory }}
        
    - name: yarn test
      run: yarn test 
      working-directory: ${{ env.working-directory }}
      env:
        CI: true

    - name: set success variable
      if: success()
      run: |
      env:
        status_test: "`Test` has passed"
        color_code_test: "#2ECC71"

    - name: set failure variable
      if: failure()
      run: |
      env:
        status_test: "`Test` has failed."
        color_code_test: "#2ECC71"

    - name: send discord message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID_SUCCESS }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN_SUCCESS }}
        avatar_url: "https://i.imgur.com/YBD6GVz.png"
        color: $env.color_code_test
        username: "Novel Check Bot"
        message: $env.status_test

  lint:
        
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend
    
    strategy:
      matrix:
        node-version: [12.x]
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: yarn install
      run: yarn install --frozen-lockfile
      working-directory: ${{ env.working-directory }}
    
    - name: yarn lint
      run: yarn lint
      working-directory: ${{ env.working-directory }}

    - name: set success variable
      if: success()
      run: |
      env:
        status_lint: "`Lint` has passed"
        color_code_lint: "#2ECC71"

    - name: set failure variable
      if: failure()
      run: |
      env:
        status_lint: "`Lint` has failed."
        color_code_lint: "#2ECC71"

    - name: send discord message
      uses: appleboy/discord-action@master
      with:
        webhook_id: ${{ secrets.WEBHOOK_ID_SUCCESS }}
        webhook_token: ${{ secrets.WEBHOOK_TOKEN_SUCCESS }}
        avatar_url: "https://i.imgur.com/YBD6GVz.png"
        color: $env.color_code_lint
        username: "Novel Check Bot"
        message: $env.status_lint